### ISSUE TITLE
mod_fastcgi failed to build on 10.11.2

### ISSUE THREAD

**Issue by mackoj** [Homebrew/homebrew-apache#104] opened 2015-12-29 15:19 UTC
Hi,

Apparently `brew install homebrew/apache/mod_fastcgi` failed on OS X 10.11.2

https://gist.github.com/anonymous/eb87f38551b6729a6d06

https://github.com/Homebrew/homebrew/issues/47499

**Comment by javian** [comment] 2016-08-31 19:41
Duplicate of #105 , closing.

**Closed by javian** 2016-08-31 19:41 UTC
