### ISSUE TITLE
httpd24 apxs hardcodes apr path

### ISSUE THREAD

**Issue by rkitover** [Homebrew/homebrew-apache#126] opened 2016-08-21 07:14 UTC
I get the following error building php:

```
apxs:Error: /usr/local/Cellar/apr/1.5.2/libexec/bin/apr-1-config not found!.
```

But the current apr bottle is in:

```
/usr/local/Cellar/apr/1.5.2_1/
```

Making a symlink allows php to build successfully, as a workaround.

This script will reproduce the problem:

```bash
brew update
brew uninstall --force httpd24 apr
brew cleanup
brew tap homebrew/apache
brew install httpd24 apr
brew tap homebrew/php
brew -v install php71 --with-homebrew-apxs
```

**Comment by edhgoose** [comment] 2016-08-21 22:42
I can confirm the same problem, and the following symlink fixed it as suggested:

`ln -s /usr/local/Cellar/apr/1.5.2_1/ /usr/local/Cellar/apr/1.5.2`

**Comment by rkitover** [comment] 2016-08-21 23:12
@edhgoose just make sure to delete the symlink before you do a `brew cleanup` or it will nuke your apr.

**Comment by javian** [comment] 2016-08-23 04:21
Just issuing `apxs -q` will show the error. It doesn't seem to pick up on the revisioned versions of apr/apr-util which causes the path error and why the soft link works.

**Comment by javian** [comment] 2016-08-23 04:37
My install seems to be working fine after `brew reinstall -s httpd24` so a revision update of Apache should resolve the issue and update the bottles.

**Comment by javian** [comment] 2016-08-23 04:39
Now that I see that https://bot.brew.sh/job/Homebrew%20Apache%20Pull%20Requests/64/version=mavericks/console I remembered that I also rebuilt apr and apr-util as well from source before rebuilding httpd24 so there might be another formula that needs revisioned before it will work.

**Comment by javian** [comment] 2016-08-23 04:48
`brew reinstall apr-util -s` seems to be required before issuing `brew reinstall httpd24 -s` which then results in the error disappearing.

**Comment by rkitover** [comment] 2016-08-23 10:29
To prevent the same thing from happening again, I would suggest for the apache build to look for `apr` in `/usr/local/opt/apr` instead of the keg location in `/usr/local/Cellar/apr/...`.

**Comment by javian** [comment] 2016-08-24 17:19
@rkitover I'm looking to see if I can find the right setting. The paths either come from apr-util in somewhere in the apache config files but I haven't been able to work out which config generates the paths.

**Comment by javian** [comment] 2016-08-25 04:03
In the apr-1-config and apu-1-config bash scripts there's a variable called "prefix" which needs to be changed. An update to the `apr` and `apr-util` Formulas should solve this.

**Comment by DomT4** [comment] 2016-08-29 16:20
Should be fixed by https://github.com/Homebrew/homebrew-core/pull/4333.

**Closed by DomT4** 2016-08-29 16:20 UTC

**Comment by sebastienbarre** [comment] 2016-11-27 03:35
I think the issue is very much going on as of today:
```
$ brew install homebrew/apache/mod_fastcgi --with-homebrew-httpd22
==> Installing mod_fastcgi from homebrew/apache
==> Downloading https://dl.bintray.com/homebrew/mirror/mod_fastcgi-2.4.6.tar.gz
Already downloaded: /Volumes/Users/barre/Library/Caches/Homebrew/mod_fastcgi-2.4.6.tar.gz
==> /usr/local/opt/httpd22/bin/apxs -o mod_fastcgi.so -c *.c
Last 15 lines from /Volumes/Users/barre/Library/Logs/Homebrew/mod_fastcgi/01.apxs:
2016-11-26 22:31:54 -0500

/usr/local/opt/httpd22/bin/apxs -o mod_fastcgi.so -c *.c

apxs:Error: /usr/local/Cellar/apr/1.5.2/libexec/bin/apr-1-config not found!.
```
where
```
$ ls -al  /usr/local/Cellar/apr/
total 0
drwxr-xr-x    3 barre  admin   102 Nov 26 22:04 ./
drwxr-xr-x  152 barre  admin  5168 Nov 26 22:31 ../
drwxr-xr-x    9 barre  admin   306 Nov 26 21:30 1.5.2_3/
```
if I manually add a 1.5.2 symlink, the problem goes to apr-util:
```
$ brew install homebrew/apache/mod_fastcgi --with-homebrew-httpd22
==> Installing mod_fastcgi from homebrew/apache
==> Downloading https://dl.bintray.com/homebrew/mirror/mod_fastcgi-2.4.6.tar.gz
Already downloaded: /Volumes/Users/barre/Library/Caches/Homebrew/mod_fastcgi-2.4.6.tar.gz
==> /usr/local/opt/httpd22/bin/apxs -o mod_fastcgi.so -c *.c
Last 15 lines from /Volumes/Users/barre/Library/Logs/Homebrew/mod_fastcgi/01.apxs:
2016-11-26 22:33:25 -0500

/usr/local/opt/httpd22/bin/apxs -o mod_fastcgi.so -c *.c

apxs:Error: /usr/local/Cellar/apr-util/1.5.4_1/libexec/bin/apu-1-config not found!.
```
where:
```
$ ls -al  /usr/local/Cellar/apr-util/
total 0
drwxr-xr-x    3 barre  admin   102 Nov 26 22:04 ./
drwxr-xr-x  152 barre  admin  5168 Nov 26 22:33 ../
drwxr-xr-x   10 barre  admin   340 Nov 26 21:25 1.5.4_4/

```
etc.
No amount of `brew reinstall apr apr-util` is fixing this issue.

**Comment by rkitover** [comment] 2016-11-27 14:57
Try something like
```bash
brew reinstall -s apr-util apr httpd24
```
to rebuild everything from source
