### ISSUE TITLE
mod_suexec build fail with error: C preprocessor "cpp" fails sanity check

### ISSUE THREAD

**Issue by PascalKern** [Homebrew/homebrew-apache#124] opened 2016-08-03 06:13 UTC
The installation of mod_suexec on my OS X Yosemite (10.10.5) Server with XCode 7.2. The Apache installation is original from the system installation.

``` bash
user:$ httpd -V
Server version: Apache/2.4.16 (Unix)
Server built:   Jul 22 2015 21:03:09
Server's Module Magic Number: 20120211:47
Server loaded:  APR 1.4.8, APR-UTIL 1.5.2
Compiled using: APR 1.4.8, APR-UTIL 1.5.2
Architecture:   64-bit
Server MPM:     prefork
  threaded:     no
    forked:     yes (variable process count)
```

While checking the preconditions I get the following error:

``` bash
user:$ brew install mod_suexec
Last 15 lines from /Users/ladmin/Library/Logs/Homebrew/mod_suexec/01.configure:
configure:
checking for APR-util... yes
checking for gcc... clang
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether clang accepts -g... yes
checking for clang option to accept ISO C89... none needed
checking how to run the C preprocessor... cpp
configure: error: in `/private/tmp/mod_suexec-20160803-561-1yxmt7r/httpd-2.4.9':
configure: error: C preprocessor "cpp" fails sanity check
See `config.log' for more details
```

Of course I ran `brew update` and `brew doctor` trying to solve the issue. All logs and outputs are available as a [gist](https://gist.github.com/PascalKern/3ea228a49101b97d57ec38d0a534e09c). 

Any idea how to overcome this issue?

**Comment by javian** [comment] 2016-08-31 21:05
The problem is that the bundled `apr-1-util --cc` returns a non-exisiting path.
You have 3 options.

1. Use a homebrewed httpd and install the module with `--with-homebrewed-httpd24` (or 22 if you use that)
2. Doing something like this at your own risk - http://stackoverflow.com/questions/11963436/changing-apr-embedded-values-returned-by-apr-1-config

**Comment by javian** [comment] 2016-09-03 14:17
The apr formulas have been fixed now - are you still seeing the issue @PascalKern ?

**Comment by PascalKern** [comment] 2016-09-08 17:31
Thanks for you response and sorry for my delayed answer. Had to fix some other issues and no time to verify your suggestions.

Because I would like to use the OS X Server and therefor not changing to the brewed `httpd24` due to configuration convenience and system integration. The symlink thing would be a option but as time goes on I was to quick enough! :)
Following your second comment I tried the installation today.  But got the same error again.

To be honest I have no clue what you meant with 
> The apr formulas have been fixed... 

I see that I have apr-util installed by homebrew but it's kegs-only and not on my PATH. May be a silly question but do I have to take any action to let brew use this apr-util? And to clarify this also, is it ether possible to use the mod_suexec formula with OS X apache anyway?

**Comment by javian** [comment] 2016-10-15 10:39
As far as I know it should be possible to use it with osx apache but I've not done it myself. As for my apr comment there was some problem at one point which I can't recall now that had been fixed which I assume is related to the path statement above.

**Comment by MikeMcQuaid** [comment] 2017-09-29 14:57
This tap is now deprecated, sorry.

**Closed by MikeMcQuaid** 2017-09-29 14:57 UTC
