### ISSUE TITLE
homebrew/apache/mod_fastcgi failed to build on 10.11.2

### ISSUE THREAD

**Issue by bfontaine** [Homebrew/homebrew-apache#105] opened 2015-12-29 15:45 UTC
_From @mackoj on December 29, 2015 15:18_

Hi,

Apparently `brew install homebrew/apache/mod_fastcgi` failed on OS X 10.11.2

https://gist.github.com/anonymous/eb87f38551b6729a6d06

_Copied from original issue: Homebrew/homebrew#47499_

**Comment by lotyrin** [comment] 2016-05-26 22:36
Also affected.

https://gist.github.com/anonymous/6e5a46ac5090ad0f9e7b154c50c3340b

**Comment by lotyrin** [comment] 2016-05-26 22:41
This is the issue described in the Readme's Troubleshooting section.

https://github.com/Homebrew/homebrew-apache#troubleshooting

**Comment by bfontaine** [comment] 2016-05-27 08:05
@lotyrin Yep; IIRC we should be able to fix this by shipping a patched `apr-1-config` but I haven’t got the time to look at it yet.

**Comment by monnoval** [comment] 2016-07-20 06:29
I recently have this issue in El Capitan (10.11.5), the issue was mainly caused by `/usr/local/Cellar/apr/1.5.2/libexec/build-1/libtool`
Edit the file itself then replace from `SED="/usr/local/Library/ENV/4.3/sed"` to `SED="/usr/bin/sed"`

**Comment by javian** [comment] 2016-08-24 17:54
@monnoval that error required a bottle update or compilation from source and should be fixed now.

**Comment by MikeMcQuaid** [comment] 2017-09-29 14:56
This tap is now deprecated.

**Closed by MikeMcQuaid** 2017-09-29 14:56 UTC
